version: "3.8"

services:
  api:
    container_name: FastAPI
    build: ./backend
    ports:
      - "80:80"
    environment:
        - DB_HOST=mongo
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - SECRET_KEY=${SECRET_KEY}

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo-database:/database

  mongo_express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo # mongoコンテナが起動してから起動させる
volumes:
  mongo-database: